# Generated by Django 4.2.1 on 2023-05-26 07:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('miniapp', '0004_userprofile_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='name',
        ),
    ]
